version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongovolume:/data/db
    networks:
      - whatsnetwork
    ports:
      - '27017:27017'
  
  servidorapi:
    container_name: servidorwhats
    restart: always
    build: 
      context: ./servidorAPI
      dockerfile: Dockerfile
      args:
        HOST: mongo
        PORT: 27017
        USERNAME: ${USERNAME}
        PASSWORD: ${PASSWORD}
        AUTHSOURCE: ${AUTHSOURCE}
        DB: ${DB}
        COLLECTION: ${COLLECTION}
    ports:
      - '5000:5000'
    networks:
      - whatsnetwork
    depends_on:
      - mongo

networks:
  whatsnetwork:
    driver: bridge